FROM node as build
WORKDIR /client
COPY ["package.json", "yarn.lock", "./"]
RUN yarn
COPY . .
RUN yarn build

FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /client/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]