os: linux
dist: trusty
services:
  - docker
install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
before_script:
  - make start
script:
  - make test
after_script:
  - make down
