os: linux
dist: trusty
language: python
python:
  - '3.6'
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install docker-compose
before_script:
  - make dev
script:
  - make test
after_script:
  - make down
env:
  global:
    - secure: B1W9OYxRrrX0eo2cIqjFIAvGpDns4JGi4IsVWGUlDDppebauHHAycQQ4TYVRtt83SHlAveFMgLD+XgtQiONUubl19rZKKkYExQ6Ka8Agnt4grMUbQH6ZkDqg68VlGnZ6or2JMbzPv+vDyySM6fBnE520pjAEjgun7BLN9JP8Kee+3TAARXXj531Mnwi9+/E1uVE5xLSVnEcMOEP6kuehQmlQxLH3SMrPLVfQVDVNIiN88vqmVTDProb7k9XYz+a2f3+dKnwRLEyfDNX+XShPo75NQMOoH4qPIZ3UpWXEjKjpvBz3imRWdfrb//j1oOoKWMLKPPFkuFcjAvdaQ3hfU5O8oJ/wUdL/CpfPj2WlhDxpH1kvn7jcGzuCXiAfyoVjAFiRZzt/OVrbVSHcs45cIar2R+kDP1SpeZAjeiqwubfUlke2V+W0w6d2cn6WIX15buV7bFHJuje5ytAtyXcmeJUBZJO4vioZKcEfI1w7ToVtczZ9Kiu93nW+D9ZO7sWI4cUJxlMZElCkwNn1kDep1eGspT+92SZ4W1dGfHl1zrFQQyXdg1uBwAC4gXOBAMp7YYBOhHN92q5sNn+WhAFNTuVezBf173+AjE8rv+6BxDZwmLxQfk1FH+Y00KVmP3ojAfQ3fyk/xS4zGJnJ5g725WQmm/sQRvmKPId9J3nHH4w=
    - secure: Mlr/iLmAxbXZmG0lShE5P0wJMD9i5VnytTelaqIWIk0CBlFs+6cnNMT7McjHLM4DuNZucYD6IJ3iE0BntFPyZTzPkQbi240OEo0evcEhzcwXD0MNquTqzoKbOXZeuZWCieKxYAsHWZ2izGakyxC0X0sue4gsW8K01vIVEJlOZHSDCLD7WeRJtdHWhJTc1DxLknZfjYFG03+g7iatMqnoZpOfJuC4SwVcugLdIhMVH2h3iPSnmnj/3jBoiGMWMa9mQOPWFcC/53TV51jqur4jkdKS/4h4y7mwZuEA9MduTnbnDxjCw7flHDrHqK+RsegSxpqj7rcoFhWyyO/N+9gobOBbZmoI+H405E1BCWlpmfD7m4RYz3V5T3UIFJuugjFoX7hScXXVgSyPCMlamJ6uqg+13Zs44Y+g626Z4V8z8yayQAmwDCntPvUyETHdj59G+nuZ8bgpUK/k2XZk/rLiW2+z1hLzTv9nNNn4EyY2ND+/TcTlwui+2YDWeo0XLkc0jGnaLIaI1LmjL+orysNH60ZuF5ivRArcBLPXqJ1H+6eL1nW+PHumEdPqVkfiMqgotR4RjmoJ7FEDXweIKTYGOx7TLcB/UnoxwDBemYKFKfHV+G7PurL9GRyy/pj8s3AwSrtj+hpDKtoZ0tiZ3NkzqgD0J99TWH6KerExK7pwuP0=
    - secure: ekwtHHzzML57lNID1YmnOTt/1u7OiX1fsajkV8De5VBAxIYMntd9vL1A6Lgt0lqR8yR1sXcJkruvF2Ax8W73cMkQM8vYp49ixaCS+vPswReanvknwtDR1K0lINIWIe/7PJ5q6fyWyLagZ2gl2p5EsRB0rSveptW+xA+BAcHPyvRCte6eR8RRjU6J5htZ4biP/r+7bPuch8i+AEwFxiDxaZcoB9BtHJUBEtIwiAjgojCoQn+STDQ+kLwg2f3XuhZQHmnRCgF5M8uf5bLz4ZtrU2ONNDETLdfIRTVxMMYztqqYiv1+daBcaigzJYHHyYNgyRswVdXQndlfybca+ruos8C+qDzofqExA/xbc0TUuyGuBnO9IK0L6Whs8IlTim0qxloPF+RJfGW6G5e2IGNff+3Eb/vWFJM3TkCFhkNywCthz8NVIysgbRnoXboP3sAMuN5msCj7DRZEOB11VWmOY+v5W4102TaRFt9Mcrcjj27/e0FLfBkPHuhYDkN3n3LlCBmroZLTrcaevx8Wr26i3+Dk3eaMteRX7E5aOLZBRoXtKoTke1DPG+27xJKkUigMzHSFqfd4oqslgAEW4QBge1DINGe8VOuwqpTip+PpD8t+s4cAKTu4YQ+z1aShCG/kEBsX/F9COQc3FL3Z/rRSo+tZZmR07e/WBAnEFrQCijI=