version: "3.3"
services:
    api:
        container_name: kanby-api
        build:
            context: ./api
            dockerfile: Dockerfile.prod
        restart: always
        ports:
            - "4000:4000"
        environment:
            - PROD_DB_URI=${PROD_DB_URI}
    client:
        container_name: kanby-client
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        restart: always
        ports:
            - "80:80"
            - "443:443"
        links:
            - api
        depends_on:
            - api