version: "3.3"
services:
    api:
        container_name: kanby-api
        build: ./api
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./api:/api
            - /api/node_modules
        environment:
            - DEV_DB_URI=${DEV_DB_URI}
            - TEST_DB_URI=${TEST_DB_URI}
            - DEV_REDIS_URI=${DEV_REDIS_URI}
        links:
            - db
            - cache
        depends_on:
            - db
            - cache
    client:
        container_name: kanby-client
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        depends_on:
            - api
    db:
        container_name: kanby-db
        image: mongo
        restart: always
        volumes:
            - ./db:/data/db
    cache:
        container_name: kanby-cache
        image: redis:6.0.5-alpine
        restart: always