version: "3.3"
services:
    api:
        container_name: kanby-api
        build: ./api
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./api:/api
            - /api/node_modules
        links:
            - db
        depends_on:
            - db
    client:
        container_name: kanby-client
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        depends_on:
            - api
    db:
        container_name: kanby-db
        image: mongo
        restart: always
        volumes:
            - ./db:/data/db