version: "3.3"
services:
    api:
        container_name: kanban-api
        build: ./api
        restart: always
        ports:
            - "${API_PORT}:4000"
        volumes:
            - ./api:/api
            - /api/node_modules
        links:
            - db
        depends_on:
            - db
    client:
        container_name: kanban-client
        build: ./client
        restart: always
        ports:
            - "${CLIENT_PORT}:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        depends_on:
            - api
    db:
        container_name: kanban-db
        image: mongo
        restart: always
        ports:
            - "${DB_PORT}:27017"
        volumes:
            - ./db:/data/db