FROM node:12.16-alpine as prod
WORKDIR /api
COPY ["package.json", "yarn.lock", "./"]
RUN yarn
COPY . .
RUN yarn build

FROM node:12.16-alpine
RUN apk add --no-cache bash
WORKDIR /api
COPY ["package.json", "yarn.lock", "./"]
RUN yarn
COPY --from=prod /api/build ./build
EXPOSE 4000
CMD ["yarn", "prod"]